name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install Yarn v3
        run: |
          corepack enable
          corepack prepare yarn@3.6.3 --activate
      - run: yarn
      - run: yarn build
      - run: yarn workspace @xmtp/bot-kit-pro up
      - run: yarn workspace @xmtp/bot-kit-pro migration:run
      - run: yarn test
